### ISSUE TITLE
suggestion: immediately query (not button) and 2 API query

### ISSUE THREAD

**Issue by sky31even** [behnamazimi/merriam-webster-dictionary-extension#2]
hi there,

i've got two suggestions:
- would you consider to have an option to choose if the button shows up or immediately show the query page when selecting the words? to my mind the 1 click on the button is unnecessary.
- while i have both the demand to query in collegiate and medical dictionary , would you consider to have 2 api fucntion so that in the 1 query page it process 2 queries side by side, say, left is collegiate and right is medical dict.

thank you for reading !~~

**Comment by behnamazimi** [comment]
Hi @sky31even ,
Thank you for your suggestions. 

Your first suggestion sounds reasonable, I'll consider this as an option in settings in the next versions. 

But about your second suggestion, I think it will cause some confusion for most users, so I prefer to think more about it. if I could make a certain plan and clear UI for it I'll add it to my plans to add as a feature.

**Comment by behnamazimi** [comment]
Opening result immediately on text select feature added to v1.13. will be released tomorrow.
