### ISSUE TITLE
frequently reset to default settings

### ISSUE THREAD

**Issue by sky31even** [behnamazimi/merriam-webster-dictionary-extension#3]
hi my friend,

with time goes I find another annoying question, this extension always reset to its default api key and therefore it says out of free times....

my chrome version 106.0.5249.119

**Comment by behnamazimi** [comment]
Hey @sky31even, thank you for letting me know. I'll take care of that as soon as I can.

**Comment by behnamazimi** [comment]
Fixed in v2.0
