### ISSUE TITLE
Popup has a typo

### ISSUE THREAD

**Issue by hirehamir** [behnamazimi/merriam-webster-dictionary-extension#4]
`you FREE` should say `your FREE`, instead.

**Comment by hirehamir** [comment]
![image](https://github.com/behnamazimi/merriam-webster-dictionary-extension/assets/43425812/643c0b30-1fbb-4693-b548-6eacf56e400d)

**Comment by behnamazimi** [comment]
Thanks for your contribution. Please make sure your PR includes the relevant changes only. And please provide more context in the issue's body.

**Comment by hirehamir** [comment]
You're welcome! I updated the pull request.

**Comment by behnamazimi** [comment]
Thank you for dedicating your time to this.

**Comment by hirehamir** [comment]
You're welcome!
